version = 1
name = "SMPlayer"

[setup]
script = "npm.cmd install"

[[actions]]
name = "Dev"
icon = "play"
command = "npm.cmd run dev"

[[actions]]
name = "Build"
icon = "build"
command = "npm.cmd run build"

[[actions]]
name = "Start"
icon = "run"
command = "npm.cmd run start"

[[actions]]
name = "Typecheck"
icon = "check"
command = "npm.cmd run typecheck"
